public class Caygyi {
    public static void main() {
        System.out.println("lqtnc");
        System.out.println("onngh");
        System.out.println("mpcmo");
        System.out.println("fyqnm");
        System.out.println("gslmg");
        System.out.println("ekxah");
        System.out.println("fryfa");
        System.out.println("cwrsd");
        System.out.println("hbitq");
        System.out.println("mmhes");
        System.out.println("nocmf");
        System.out.println("hguxn");
        System.out.println("mkwvu");
        System.out.println("nokdn");
        System.out.println("hqnxs");
        System.out.println("hldwc");
        System.out.println("ynwcc");
        System.out.println("dlicw");
        System.out.println("fjyxw");
        System.out.println("coivi");
        System.out.println("mpumv");
        System.out.println("kpsvl");
        System.out.println("sxdaw");
        System.out.println("uxnca");
        System.out.println("nqgpo");
        System.out.println("dxcjd");
        System.out.println("ktnsf");
        System.out.println("jjden");
        System.out.println("nshrq");
        System.out.println("itria");
    }
}
