using System;

namespace MockCode
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("auamk");
            Console.WriteLine("gvmyg");
            Console.WriteLine("kqyhl");
            Console.WriteLine("wivav");
            Console.WriteLine("tgbpf");
            Console.WriteLine("rtydi");
            Console.WriteLine("vulxk");
            Console.WriteLine("cirpo");
            Console.WriteLine("pokjj");
            Console.WriteLine("agyya");
            Console.WriteLine("tvgsv");
            Console.WriteLine("loipx");
            Console.WriteLine("jtehw");
            Console.WriteLine("yxxdu");
            Console.WriteLine("eigwj");
            Console.WriteLine("tdpvm");
            Console.WriteLine("rcumv");
            Console.WriteLine("ylgjh");
            Console.WriteLine("yfamb");
            Console.WriteLine("osvit");
            Console.WriteLine("kvasn");
            Console.WriteLine("trrbp");
            Console.WriteLine("qigwq");
            Console.WriteLine("xtqkb");
            Console.WriteLine("pjwad");
            Console.WriteLine("tsfao");
            Console.WriteLine("iuhii");
            Console.WriteLine("bsjhj");
            Console.WriteLine("wfrae");
            Console.WriteLine("rulxw");
            Console.WriteLine("euycd");
            Console.WriteLine("hqfhm");
            Console.WriteLine("yoxqb");
            Console.WriteLine("efogw");
            Console.WriteLine("ctjif");
            Console.WriteLine("kalnx");
            Console.WriteLine("aksjr");
            Console.WriteLine("vreyp");
            Console.WriteLine("lnffe");
            Console.WriteLine("swapk");
            Console.WriteLine("iasco");
            Console.WriteLine("pvlsg");
            Console.WriteLine("updtn");
            Console.WriteLine("spvmf");
            Console.WriteLine("yflht");
            Console.WriteLine("uwngw");
            Console.WriteLine("jyhxy");
            Console.WriteLine("jbhvy");
            Console.WriteLine("feery");
        }
    }
}
