using System;

namespace MockCode
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("auamk");
            Console.WriteLine("gvmyg");
            Console.WriteLine("kqyhl");
            Console.WriteLine("wivav");
            Console.WriteLine("tgbpf");
            Console.WriteLine("rtydi");
            Console.WriteLine("yramb");
            Console.WriteLine("vptin");
            Console.WriteLine("crndv");
            Console.WriteLine("xjutd");
            Console.WriteLine("ammuw");
            Console.WriteLine("towky");
            Console.WriteLine("sevsk");
            Console.WriteLine("bwfsc");
            Console.WriteLine("vpwbu");
            Console.WriteLine("prdhi");
            Console.WriteLine("vnmeq");
            Console.WriteLine("wbuov");
            Console.WriteLine("kkair");
            Console.WriteLine("xiyad");
            Console.WriteLine("yixbn");
            Console.WriteLine("vmegt");
            Console.WriteLine("jmsao");
            Console.WriteLine("mjvdc");
            Console.WriteLine("oiiup");
            Console.WriteLine("agvpt");
            Console.WriteLine("xrkqd");
            Console.WriteLine("kxgfl");
            Console.WriteLine("ricvb");
            Console.WriteLine("tdwsb");
            Console.WriteLine("vdnrm");
            Console.WriteLine("tjjhf");
            Console.WriteLine("hkbpb");
            Console.WriteLine("hdyqs");
            Console.WriteLine("ottmj");
            Console.WriteLine("bkgvb");
            Console.WriteLine("ajgfm");
            Console.WriteLine("udcjh");
            Console.WriteLine("dnsfv");
            Console.WriteLine("bxnmd");
            Console.WriteLine("tjyxy");
            Console.WriteLine("nghdn");
            Console.WriteLine("fwbrf");
            Console.WriteLine("hbbfu");
            Console.WriteLine("rueek");
            Console.WriteLine("iocis");
            Console.WriteLine("rrphb");
            Console.WriteLine("ndfxo");
            Console.WriteLine("nrsep");
            Console.WriteLine("qloos");
            Console.WriteLine("vcnly");
            Console.WriteLine("oieue");
            Console.WriteLine("ikebm");
            Console.WriteLine("pdxwa");
            Console.WriteLine("sqxgm");
            Console.WriteLine("cneoa");
        }
    }
}
