using System;

namespace MockCode
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("auamk");
            Console.WriteLine("gvmyg");
            Console.WriteLine("kqyhl");
            Console.WriteLine("wivav");
            Console.WriteLine("tgbpf");
            Console.WriteLine("rtydi");
            Console.WriteLine("btsmo");
            Console.WriteLine("jsfrv");
            Console.WriteLine("hgkxy");
            Console.WriteLine("ngkxt");
            Console.WriteLine("curbv");
            Console.WriteLine("slmuh");
            Console.WriteLine("tuwyk");
            Console.WriteLine("fkhrj");
            Console.WriteLine("vgljv");
            Console.WriteLine("ohgjr");
            Console.WriteLine("fukmh");
            Console.WriteLine("wxcyy");
            Console.WriteLine("mtlrf");
            Console.WriteLine("ldhkt");
            Console.WriteLine("artos");
            Console.WriteLine("lnwed");
            Console.WriteLine("efnot");
            Console.WriteLine("splff");
            Console.WriteLine("djnne");
            Console.WriteLine("byxdu");
            Console.WriteLine("ybbbg");
            Console.WriteLine("vwifc");
            Console.WriteLine("oiqhy");
            Console.WriteLine("xyyno");
            Console.WriteLine("luihn");
            Console.WriteLine("rurps");
            Console.WriteLine("tcwqa");
            Console.WriteLine("udjcp");
            Console.WriteLine("bygdr");
            Console.WriteLine("kpayf");
            Console.WriteLine("yqvbh");
            Console.WriteLine("hliby");
            Console.WriteLine("ugkqx");
            Console.WriteLine("tqwes");
            Console.WriteLine("xoirm");
            Console.WriteLine("wvvas");
            Console.WriteLine("kxtlb");
            Console.WriteLine("tiker");
            Console.WriteLine("jdtci");
            Console.WriteLine("rnpdl");
            Console.WriteLine("cfxas");
            Console.WriteLine("fijgb");
            Console.WriteLine("kenvw");
            Console.WriteLine("lgddi");
            Console.WriteLine("whnyf");
            Console.WriteLine("inuyj");
        }
    }
}
